### ISSUE TITLE
ANCIENT_RUNE_VILLAGERS doesn't work on old villagers

### ISSUE THREAD

**Issue by bobhenl** [Slimefun/Slimefun4#2592]
## :round_pushpin: Description (REQUIRED)

Hi, when I use ancient rune villagers on old villagers it doesn't work. Players reported me this issue few days ago. When I tested it on player's villagers, it was really true. On newly spawned villagers this rune worked, but on the old ones it didn't.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Try use ancient rune villagers on older villagers from your players.
You'll see something like:
https://streamable.com/u04jd2
His NBT tags: https://streamable.com/qdiuj6
Tested once more: https://streamable.com/qe7gqm

Newly spawned villagers work, proof:
https://streamable.com/ujvc06

His NBT tags: https://streamable.com/icllnx

## :bulb: Expected behavior (REQUIRED)

This rune should work on older villagers too, but from some reason it didn't.
## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.4
 - Slimefun Version: 765
 - CS-CoreLib Version: 92

**Comment by TheBusyBiscuit** [comment]
??
In your video you right click a villager with a profession with a rune and it removes their job.
That's exactly what the rune is supposed to...

**Comment by bobhenl** [comment]
But the problem is he doesn't get job again.... that's the problem. AS you can see when I tried give him job again.

**Comment by TheBusyBiscuit** [comment]
That is completely normal.

**Comment by bobhenl** [comment]
But ancient rune should work like when we reset his job, then he could get new job, no? And in this video he can't get new job... Why you wanna reset villager, if he can't get job then?

**Comment by dniym** [comment]
I think the issue here is in both the “old villager” videos you never break the workstation the villager is linked to internally.  

This won’t let the Minecraft AI look for a new one because it thinks it still has a job. 

I would just about bet if you try the newly spawned villager and don’t break the workstation the new one won’t pick up a job either.  

The villager api from spigot is quite limited but slowly improving there may be a method to clear the workstation eventually but currently I don’t see one without going into nms or screwing around with the NBT data
