### ISSUE TITLE
Slimefun guide history doesn't retain pagination for the main menu

### ISSUE THREAD

**Issue by bobhenl** [Slimefun/Slimefun4#2593]
## :round_pushpin: Description (REQUIRED)

Hi, I have issue (reported by players) in SF guide. When players open category on another page, for ex. on page 2, then when they click back button they aren't returned to previous page (the second), but to the first one, always. And they probably should be returned back to previous page, so page 2, it's a little bit annoying for them when they open category on page 2, then they click on back, appear on the first page, and have to click again on page 2 and then on another category... and imagine you're searching through categories and this really annoys you.

Same for sf cheat.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give yourselves sf guide.
2. Open it.
3. Go on the next page (for ex. 2, may you need to add addons there).
4. Click on previous page (back button).
5. Now you're on the first page instead on the second one.
https://streamable.com/cmixva

## :bulb: Expected behavior (REQUIRED)

It should go back to the second page, not to the first one, because it's annoying for players when they have to click and click through pages and then categories again and again.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.4
 - Slimefun Version: 765
 - CS-CoreLib Version: 92

**Comment by bobhenl** [comment]
There's video, why it needs testing?

**Comment by brettsaunders21** [comment]
Tested with version's reported:

- Server Software (Spigot/Paper): Paper
- Minecraft Version: 1.16.4
- Slimefun Version: 765
- CS-CoreLib Version: 92
And confirmed as present in this version.

Also tested with the latest dev version of Slimefun where the issue is still present.
- Server Software (Spigot/Paper): Paper
- Minecraft Version: 1.16.5
- Slimefun Version: 801
- ClayTech: 1.2.19
- Liquid: 9
- ExtraHeads: 20
- DynaTech: 35
- EcoPower: 3
- HotbarPets: 35
- ExtraGear: 12

As reported by issue author the addons don't matter, just need enough installed to have a second page in the guide.
