### ISSUE TITLE
Killing iron golems does not drop circuit board

### ISSUE THREAD

**Issue by natnat729** [Slimefun/Slimefun4#2618]
## :round_pushpin: Description (REQUIRED)
 
 

I killed iron golems and even though I researched the board It still did not drop after killing 6 golems

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Research basic circuit board
2. Make iron golem
3. Kill iron golem

IMG_3084.HEIC
![7EB786F8-E400-4A1F-8C02-1B99C9665A64](https://user-images.githubusercontent.com/75842077/101905139-f5c54480-3b84-11eb-8d22-34c8077357ab.jpeg)
![B26EC1DC-EC3B-48A6-80A0-C1E040F00ECE](https://user-images.githubusercontent.com/75842077/101905146-f8c03500-3b84-11eb-9002-021bfa6591da.jpeg)
![48A113F3-A51B-4A49-95D0-226D4D98A1C5](https://user-images.githubusercontent.com/75842077/101905149-f958cb80-3b84-11eb-94ae-a77d993530b3.jpeg)
![09171779-8C06-4710-9C12-B2391F1F2AB5](https://user-images.githubusercontent.com/75842077/101905151-f9f16200-3b84-11eb-93bf-caadc5e5e46e.jpeg)

## :bulb: Expected behavior (REQUIRED)

I expected it to drop one but after killing six I still don’t have one I don’t know if it’s a very rare drop I have looting 3 but I still don’t have one

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version:
 - Slimefun Version:
 - CS-CoreLib Version:

**Comment by TheBusyBiscuit** [comment]
The drop is chance-based, you won't be guaranteed to get a circuit board everytime.
Also, missing versions.

**Comment by J3fftw1** [comment]
Could also be a mob stacker thats in the way of dropping

**Comment by natnat729** [comment]
The version is 1.16.4 I think

**Comment by natnat729** [comment]
Yeah it is

**Comment by natnat729** [comment]
What’s the drop rate?

**Comment by natnat729** [comment]
Because I’ve killed 8 and 2 of them have been killed with looting 3

**Comment by WalshyDev** [comment]
# Having problems with mob drops?
Mob stackers will modify drops but sadly most of them don't handle custom drops correctly. If you're not getting things like _basic circuit boards_ please consider changing your mobstacking plugin. 

We personally suggest [StackMob](<https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance-without-the-sacrifice.29999/>) where you can modify this as a config option. Set `use-loot-tables` to `false` and custom drops will work!

> **Note:** We are not the developers of StackMob or any other stacker plugins. This is just one we recommend based on experience from other Server Owners. Report bugs to the correct author!


Now please stop spamming comments. If you are using a mob stacker see above. Otherwise, we need actual info. All your versions (/sf versions), your plugin list, your config.

Also, for the love of god, use a screenshot tool (theres one built into Windows man - Win+Shift+S)
