### ISSUE TITLE
TPS Falls

### ISSUE THREAD

**Issue by TheSavior22** [Slimefun/Slimefun4#2632]
## :round_pushpin: Description (REQUIRED)

Hello, first of all I apologize, I do not know if help is asked in this way, but I do not know what to do, I tried to join the discord but I get an error, my server is suffering a long delay and this is expressed in drops of tps, my server has 13 gb of ram and these are its specifications • Intel® Core ™ i9 or AMD Ryzen ™ 7/9 Processor
• 13GB DDR4 RAM

Here I leave you a timing report of aikar, I really appreciate your help, I will leave the list of addons present, thanks u guys
https://timings.aikar.co/?id=dce78d3891484f65bfd854657ec5e70e

## :compass: Environment (REQUIRED)

Installed Addons: (30)
GlobalWarming vDEV - 4 (git bd8e730a)
ExtraTools vDEV - 23 (git 9299a65c)
FoxyMachines vDEV - 9 (git 27240b97)
SlimefunOreChunks vDEV - 10 (git 91df3b8e)
SensibleToolbox vDEV - 36 (git bcb849b5)
ExtraGear vDEV - 12 (git 4570ea2c)
MoreTools vDEV - 8 (git db8d8814)
ClayTech v1.2.19
InfinityExpansion vDEV - 51 (git fc1a547e)
SFCalc vDEV - 14 (git 8d205b67)
ElectricSpawners vDEV - 18 (git f9da206b)
ExtraHeads vDEV - 18 (git ec4e19f2)
MobCapturer vDEV - 11 (git 4edf38dd)
SlimyTreeTaps vDEV - 16 (git 46272e92)
ColoredEnderChests vDEV - 17 (git f9a39e70)
TranscEndence vDEV - 22 (git 7660c9f0)
FluffyMachines vDEV - 54 (git e23b38fb)
ChestTerminal vDEV - 38 (git c024be5c)
DyedBackpacks vDEV - 11 (git b8eda0c7)
SoundMuffler vDEV - 18 (git fd181e0d)
SlimefunWarfare vDEV - 11 (git 001a2946)
EcoPower vDEV - 2 (git b0c0c875)
HotbarPets vDEV - 32 (git 977f0591)
SlimefunLuckyBlocks vDEV - 30 (git 26824119)
ExoticGarden vDEV - 63 (git b7dfe8c3)
Barrels vDEV - 14 (git 1563de94)
Liquid vDEV - 5 (git fabacb37)
LiteXpansion vDEV - 100 (git cae4353e)
SoulJars vDEV - 18 (git 098ad836)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.4
 - Slimefun Version: Slimefun4 - DEV 766 (git 5aa5c).jar
 - CS-CoreLib Version: CS-CoreLib - DEV 92 (git e9150).jar

**Comment by J3fftw1** [comment]
First of all the specs you listed are complete non sense
You are on a shared host so you share resources a known fact of all shared hosts are that they over sell so less recourses for all their clients
You run a few server intensive addons aswell i havent looked at your timings at all but take a look at this first see if this helps
https://github.com/Slimefun/Slimefun4/wiki/Server-Optimizations
If it doesnt comment back here

**Comment by WalshyDev** [comment]
# Experiencing lag?
There are lots of potential sources for lag, so it is important to first understand how to identify it.

## 1. Identifying the source of lag
We wholeheartedly recommend you to use ⚡ [Spark](https://www.spigotmc.org/resources/spark.57242/).
Run the command `/spark sampler --thread * --timeout 300` and wait **5 minutes**.
You should get an extensive lag profile of your server now, feel free to send us the resulting url.

## 2. Profiling with Slimefun
If you or someone else feels like it's Slimefun at fault, proceed by running 
`/sf timings` and `/sf versions`.
Send screenshots of both commands, also hover over the details sections in the timings menu and screenshot these too.

## 3. What can I do to combat lag caused by Slimefun?
We have written an extensive guide about [Server Optimizations](https://github.com/Slimefun/Slimefun4/wiki/Server-Optimizations) on our Slimefun4 wiki. Check it out for more info on how to optimize your Server.

**Comment by WalshyDev** [comment]
Cargo seems to be all of your "TPS loss" (note it's 13ms/tick) which is below 1 tick (50ms) meaning that alone isn't causing a TPS drop. So, configure that and look at your other plugins (as some are causing much more than SF).

**Comment by TheSavior22** [comment]
https://spark.lucko.me/#IFrxvt2C4F

if you can help me, 
already optimize spigot, paper and slimefun: c

**Comment by J3fftw1** [comment]
Join the discord server its working again

**Comment by andris155** [comment]
@WalshyDev If I create issue a spark and timings link and what is causes lag in Slimefun will you accept it on GitHub and possibly make a fix?

**Comment by TheBusyBiscuit** [comment]
> @WalshyDev If I create issue a spark and timings link and what is causes lag in Slimefun will you accept it on GitHub and possibly make a fix?

No.
If you are having performance issues, we are gonna handle it on discord.
