### ISSUE TITLE
Block machine duplication bug

### ISSUE THREAD

**Issue by GenericEntity579** [Slimefun/Slimefun4#2771]
## :round_pushpin: Description (REQUIRED)

A block based Slimefun machine duplication bug.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1.  Place down Slimefun machine.
2.  Equip Pickaxe in main hand.
3.  Equip easily broken block in off hand.
4.  Shift and hold down right click button as you break the machine.
https://user-images.githubusercontent.com/49162768/105759160-1cb1bd00-5f1e-11eb-8320-dbe217f216d8.mp4

## :bulb: Expected behavior (REQUIRED)

The machine breaks and drops one item form of itself instead of duplicating.

## :scroll: Server Log

No errors or logs.

## :open_file_folder: /error-reports/ Folder

No errors or logs.

## :compass: Environment (REQUIRED)

**Server Version:** Purpur git-Purpur-961 (MC: 1.16.5)
**Slimefun Version:** Slimefun vDEV - 795 (git 17fd2ec5)
Metrics build: 20

Installed Addons: (8)
DyedBackpacks vDEV - 13 (git 964b2d55)
ExtraTools vDEV - 23 (git 9299a65c)
SFCalc vDEV - 14 (git 8d205b67)
LiteXpansion vDEV - 124 (git 0e449831)
EcoPower vDEV - 3 (git 18ba903d)
SlimyTreeTaps vDEV - 17 (git 8f3e755b)
FluffyMachines vDEV - 64 (git 582f5de7)
ExoticGarden vDEV - 67 (git 7ee391e1)

**Comment by brettsaunders21** [comment]
Tested and Confirmed as a bug following the steps listed above.

While testing I found that it couldn't get this to work with an unenchanted diamond pickaxe, but could with an unenchanted Netherite.
The issue appears to be related to breaking the block so quickly and placing another that Slimefun drops two items instead of one.

Managed to replicated it with multiple blocks including the Electric Smeltery and Electric Furance.

🧭 Environment (REQUIRED)
Server Version: Paper 439 (MC: 1.16.5)
Slimefun Version: Slimefun vDEV - 801
