### ISSUE TITLE
MultiBlockInteractEvent setCancelled not work

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2809]
## :round_pushpin: Description (REQUIRED)

The MultiBlockInteractEvent setCancelled not work.
I try disable the MultiBlock machines in creative mode, but the e.setCancelled(true) not working. The multiblock machines still works.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Use the MultiBlockInteractEvent api and setup the e.setCancelled(true).

## :bulb: Expected behavior (REQUIRED)

MultiBlockInteractEvent setCancelled(true) works, and if true, the multiblocks machines no usable.

## :open_file_folder: /error-reports/ Folder

https://pastebin.com/EMqzZuNi

## :compass: Environment (REQUIRED)

Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
Slimefun DEV - 812 (git 47743b63)
Metrics-Module #21
Java 11

Installed Addons: (2)
  RestrictedCreative v2.4.6
  SlimefunFix v1.1-SNAPSHOT

**Comment by WalshyDev** [comment]
The event is named interact rather then use so I understand why it may not block usage.

However, it is a cancellable event so it isn't doing what it should regardless.
The interact handler is currently firing before the event and event result is ignored.
Ref: https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MultiBlockListener.java#L65-L66

This event name indicates it's pre really and since it's cancellable it should do something.

**Comment by andris155** [comment]
Big thanks for this. :)
