### ISSUE TITLE
Missing Research

### ISSUE THREAD

**Issue by Solverbolt** [Slimefun/Slimefun4#3368]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Only able to research 173 out of 174 of the total research. One is missing and not showing up.

### 📑 Reproduction Steps

1. Grind hundreds of levels of experience
2. Start Learning every research Tree
3. When performing /sf stats check after learning every tree, finding that one research block is not showing up in the book, but does for the stats log. 

### 💡 Expected Behavior

Being able to see all research would be the expected behaivor 

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/38087746/145513757-1f178f43-fee9-43bc-add8-1840c12141e6.png)
![image](https://user-images.githubusercontent.com/38087746/145513798-c0cece1c-4fc8-42a7-b8ea-f210322fbd40.png)
![image](https://user-images.githubusercontent.com/38087746/145513822-d1e40489-5eaa-42db-a580-65a439d365dc.png)
![image](https://user-images.githubusercontent.com/38087746/145513841-40971c0b-25ac-4969-8d54-afc0b7c850a1.png)
![image](https://user-images.githubusercontent.com/38087746/145513880-fbfa24b8-7321-41bc-b5a6-421211a10069.png)
![image](https://user-images.githubusercontent.com/38087746/145513898-d1c36528-dde1-4e07-9740-0d961bb152e5.png)
![image](https://user-images.githubusercontent.com/38087746/145513925-059795a4-a79b-4b0b-a542-0e7fd8bf1971.png)
![image](https://user-images.githubusercontent.com/38087746/145513945-4a2a047b-167f-4a36-8dad-7ce02df888e1.png)
![image](https://user-images.githubusercontent.com/38087746/145513965-ea829c7a-4785-433d-9583-212f511729e4.png)
![image](https://user-images.githubusercontent.com/38087746/145513989-4d2a0f36-43d9-4e0b-a201-5aa32a1fc018.png)
![image](https://user-images.githubusercontent.com/38087746/145514018-599e204f-8820-42c1-8ef7-bbb3052efe84.png)
![image](https://user-images.githubusercontent.com/38087746/145514043-a1560834-1d8e-4499-be58-09e98ee847fe.png)
![image](https://user-images.githubusercontent.com/38087746/145514074-4cdbbd84-4df1-41e7-9462-9259a56d0a04.png)
![image](https://user-images.githubusercontent.com/38087746/145514096-6fc73c89-22b8-440b-9ba4-14909f569ac6.png)
![image](https://user-images.githubusercontent.com/38087746/145514127-007362d6-fa39-4354-a5a4-f4d7f3815f11.png)
![image](https://user-images.githubusercontent.com/38087746/145514151-659d2de1-1b54-4c05-adc4-24f404d6a275.png)
![image](https://user-images.githubusercontent.com/38087746/145514172-ae4dcd63-4284-441f-9d77-06e9c9684ddf.png)
![image](https://user-images.githubusercontent.com/38087746/145514200-905a6531-3af9-416d-a510-e85f63b5bbe2.png)
![image](https://user-images.githubusercontent.com/38087746/145514227-160cc3b0-6b5f-45c6-ac71-3a9f26a638c2.png)
![image](https://user-images.githubusercontent.com/38087746/145514247-e4dfd708-0baa-479b-bfbe-447c46f03934.png)
![image](https://user-images.githubusercontent.com/38087746/145514264-eb2b6bc8-4d9b-45f1-8f8d-bfffb7eb332a.png)
![image](https://user-images.githubusercontent.com/38087746/145514292-852567e2-900e-42a8-9e27-4e1da0bc9015.png)
![image](https://user-images.githubusercontent.com/38087746/145514311-b586ef86-67f4-4cba-990b-4d229adb20de.png)
![image](https://user-images.githubusercontent.com/38087746/145514339-d1eaaa05-ff59-4859-84af-45337cf56939.png)
![image](https://user-images.githubusercontent.com/38087746/145514352-da326a76-7646-4bc4-950d-d0cf64e28991.png)
![image](https://user-images.githubusercontent.com/38087746/145514372-951032bc-50c6-4f29-8e79-1144e9036fb9.png)
![image](https://user-images.githubusercontent.com/38087746/145514396-ab198579-f020-42bb-b341-6c6900bb9698.png)
![image](https://user-images.githubusercontent.com/38087746/145514419-9bae92aa-5aec-4c64-8d27-6c325fde39ff.png)
![broken slimefun](https://user-images.githubusercontent.com/38087746/145514700-4d3fbea4-7866-4335-a608-c55a7587240c.png)

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Minecraft 1.17.1-R0.1-SNAPSHOT
Slimefun: Dev - 985 (git 1f3d0f5c)

### 🧭 Other plugins

Economy
MCMMO
Tech and Magic
Quests and NPC
Custom Enchant
Many Achievements 
Crates
Player Shops
Claim System (golden shovel)

**Comment by Sfiguz7** [comment]
Could you check you `items.yml` and ctrl+F for any `enabled: false` items? If you disable all the items related to one research you are never going to be able to... Well research it, and as of now the stats are based on unlocked researches over total existing researches.
Just yesterday this came up in Discord here https://discordapp.com/channels/565557184348422174/569249847258120222/918455136760758302, the viabiliy of moving stats to unlocked items over total enabled items is still under discussion as you can see in the chat

**Comment by Solverbolt** [comment]
I will look into that.  I will get back to you once I have more information. I am only a moderator, so will have to run this up the chain. But thank you for you response.

**Comment by variananora** [comment]
Found the issue of this. This happened because some Slimefun research are actually just a normal vanilla Minecraft items. Below listed all the affected items. The number beside it indicates what are the research id is.

I think this is an oversight in the research code, since you can't use the item that haven't been researched, that is why this vanilla items just being bypassed. (Idk why elytra works tho? probably because it have other items?)

- 74 Chainmail Armors
- 111 Armored Jetpack (the item doesnt even exist)
- 249 Totem of Undying
- 279 Trident


<details>
<summary>Affected items in the `ResearchSetup.java`</summary>

https://github.com/Slimefun/Slimefun4/blob/35e25eb8596c413ef1d60e0187ce7f1b78e3dce8/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java#L104

https://github.com/Slimefun/Slimefun4/blob/35e25eb8596c413ef1d60e0187ce7f1b78e3dce8/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java#L133

https://github.com/Slimefun/Slimefun4/blob/35e25eb8596c413ef1d60e0187ce7f1b78e3dce8/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java#L259

https://github.com/Slimefun/Slimefun4/blob/35e25eb8596c413ef1d60e0187ce7f1b78e3dce8/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/setup/ResearchSetup.java#L291

</details>


<details>
<summary>`/sf stats`</summary>
```
[CHAT] Statistics for Player: variananora
[CHAT] Title: Proficient Master
[CHAT] Research Progress: 98.45 % (254 / 258)
[CHAT] Total XP Levels spent: 5346
```
</details>

<details>
<summary>Server details and video</summary>

https://youtu.be/rnbiQ2NSAYs

![image](https://user-images.githubusercontent.com/34732414/147518385-8162bd66-4d0a-474d-b77f-65c60ae02e44.png)


</details>
