### ISSUE TITLE
Electric Ore Grinder continuing to craft even if it is full

### ISSUE THREAD

**Issue by marvjosh1** [Slimefun/Slimefun4#3525]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When using the recipe diamonds > 4 carbon in the electric ore grinder, I noticed that very rarely the ore grinder will process diamonds to carbon, even when the machine is already full

### 📑 Reproduction Steps

Place down an electric ore grinder
Fill it up with diamonds
Watch it very very rarely crafting while its already full

### 💡 Expected Behavior

No items to be crafted when the machine is full

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=tZyvkgD93BY

The issue is happening at around 0:20

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

https://i.imgur.com/GbTQhbk.png

**Comment by J3fftw1** [comment]
Is this only an issue with the ore grinder or all electric machines?

**Comment by marvjosh1** [comment]
From what we have experienced until now, it is only the ore grinder.

**Comment by Boomer-1** [comment]
I've not been able to reproduce this. I've had an ore grinder sitting full with carbon on the right, and the same amount of diamonds on the left for some time. I noticed you have a lot of custom or altered slimefun plugins. Do you have a test server where you can remove them all, and just run slimefun to see if it happens?

**Comment by Boomer-1** [comment]
marvjosh1, any updates on a test server?

**Comment by marvjosh1** [comment]
No, I haven't been able to test it yet as its a pretty hard to spot thing that took a while to figure out.

Although I don't understand exactly how custom or modified addon versions would exactly interfere with how a base Slimefun machine works.

**Comment by Boomer-1** [comment]
The reason I've asked is that after a week of running ore grinders, not one has done this for me using official versions.

**Comment by TheBusyBiscuit** [comment]
Let me explain: The Ore Grinder is **not** continuing to craft if it is full.
This is just a "visual glitch" if anything.

Basically, the progress indicator on any machine is only updated if there is at least one player having the inventory opened.
The indicator will basically freeze when you close the machine but the logic of the machine itself will still continue to be run.
Once a Player opens the inventory, the indicator will be updated within a few milliseconds of delay.
It's basically just a performance saver I implemented some time ago since I figured there is no need to perform relatively expensive ItemMeta mutations when noone is even looking in the first place.
