### ISSUE TITLE
Slimefun "Block Storage" Memory Leak

### ISSUE THREAD

**Issue by Agaloth** [Slimefun/Slimefun4#3553]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

https://github.com/Slimefun/Slimefun4/blob/1a8d2bfe18ad2e6322c32e5a179731591df93dcf/src/main/java/me/mrCookieSlime/Slimefun/api/BlockStorage.java#L57

This object grows without bounds which causes a memory leak.

### 📑 Reproduction Steps

1. Just run slimefun for 18+ hours

### 💡 Expected Behavior

Memory leak

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/33335971/166120973-d5920824-e52a-4ee6-a077-2ef3e778edd2.png)
![image](https://user-images.githubusercontent.com/33335971/166120975-504413d6-03be-4e59-88bd-42162bfc23d3.png)

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Pufferfish git-Pufferfish-6 (MC: 1.17.1)
Slimefun DEV - 1014 (git f431aa6d)
Metrics-Module #28
Java 16

Installed Addons: (7)
  CMILib v1.1.1.1
  ShopGUIPlus v1.74.0
  DeluxeCombat v1.40.1
  EcoPower vDEV - 5 (git 5c1ecd68)
  ItemsAdder v3.1.2
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  ChestTerminal vDEV - 44 (git 3115957d)

**Comment by WalshyDev** [comment]
I wish people would stop opening like JProfiler (or the many likes) and jumping to memory leak on a "suspect"

The BlockStorage uses tons of memory (way more than it should) yes. That is caused by the way it's implemented (it sucks, we know). That does *not* mean it has a memory leak. Wouldn't surprise me if we did somewhere however, we'd have actual reports of there was one here.

Apparently Paper also has a memory leak if you just read a suspect and say it's confirmed.

If you dig into the data and see memory being held which shouldn't be by all means reopen the report. I'd love to fix a memory leak if we have one however, there's no information here to indicate we actually do have one. You haven't even OOM'd. I'd love to see more data if you actually do suspect a memory leak but the few times people do claim there is one, it's literally just this same screenshot... that isn't real info. It's just a suggestion there could be a memory leak due to the excessive memory being taken by a single instance (which, in this case isn't actually true)

**Comment by Agaloth** [comment]
I mean, my server do OOM's daily, it's just that one time I could catch that before it OOM'ed

**Comment by WalshyDev** [comment]
Again, if you have more data feel free to provide it. I'd love to dig into it. However, just posting a screenshot which gives nothing isn't helpful.

Are you actually seeing characteristics of a memory leak? Can you actually tie it back to Slimefun? Do you not just need more memory? What data is being held that shouldn't be?

We really need more than "ah program said you maybe leak fix now pls"

**Comment by Agaloth** [comment]
For sure, can I provide the heap and plugin list via discord? I use 16gb ram which is more than enough for minecraft.
