### ISSUE TITLE
Dupe BUG in slimefun

### ISSUE THREAD

**Issue by ReformedHooper** [Slimefun/Slimefun4#3565]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hi, does anyone have a problem with dupe bug? players can duplicate via autoenchanter, I don't know exactly how, unfortunately I didn't find out, but I know you can duplicate through it, I'll ask for a fix or an unban on a discord, I didn't write anything so terrible that I had to get a ban, I just claimed the truth.

### 📑 Reproduction Steps

-

### 💡 Expected Behavior

-

### 📷 Screenshots / Videos

-

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Dev 1014

**Comment by Sefiraat** [comment]
You were banned on Discord because of your behaviour regarding a supposed memory leak (which you have since been told is not the case both on the Slimefun Discord and also the Paper discord. 

Regardless of that fact, this issue has no where near enough information to be able to triage let alone take steps to fix this. Feel free to re-raise the issue when you have gathered enough (or any) information on this supposed dupe and I'm sure it'll be looked into regardless of your previous actions.

Thanks
