### ISSUE TITLE
Bug SlimeFun Android glitch

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#3677]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Android keeps breaking the mangrove wood endlessly because of the saplin of the wood

server version and addons: https://prnt.sc/lO89wOBSUEBi

### 📑 Reproduction Steps

using android and mangrove tree

### 💡 Expected Behavior

not endlessly generating

### 📷 Screenshots / Videos

Video: https://youtube.com/shorts/nmg8KXrE0ag

### 📜 Server Log

no have

### 📂 `/error-reports/` folder

no have

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1028 (git 1dcc4bdd)

**Comment by Boomer-1** [comment]
it might also help if you can get more details on that build, as it wasn't a mangrove log that was placed, it was an acacia log. the mangrove bark grows left to right, that went top to bottom and was orange, which is acacia. also i'm guessing you have a plugin that tells what version of mc an item was added, since that is not a vanilla or slimefun feature

**Comment by variananora** [comment]
#3678 should fix this, but jeff type it as 3577 and not 3677 lol
