### ISSUE TITLE
[CRITICAL] Duplication bugs with barrels and also when using CrateReloaded plugin

### ISSUE THREAD

**Issue by EagL3-GIT** [Slimefun/Slimefun4#3727]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I found out 2 duplication methods which kinda breaking the whole server when u know about them.

### 📑 Reproduction Steps

1. method:
u take crate key (cratereloaded plugin) and destroy that slimefun block/head with crouching 
and it drops the exact duplicate (original block stays there)
(and yes, its working in survival mode too)

2. method: 
two players, u fill the output slot and put the thing u want to duplticate in the middle
one player have to destroy the barrel in the exact time the other player take it out with SHIFT + RMB
the item stays in barrel and also in other player inventory
I mean u can do it also in 1 player but its difficult to do it that fast

### 💡 Expected Behavior

In first scenario it should not drop head/block/sf item at all when u break it with a physical key. (CrateReloaded)
In the second scenario I am not sure, just kinda prevent open it when someone using it at least? (1 player can do it too but hard)

### 📷 Screenshots / Videos

1. method: https://cdn.discordapp.com/attachments/922843416130363462/1052969049568591962/Minecraft_2022.12.15_-_16.21.42.01.mp4

2. method: https://cdn.discordapp.com/attachments/606787319583866900/1052972071463944303/dupeglitch2.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Paper git-Paper-307 (MC: 1.19.2)
Slimefun DEV - 1035 (git 0b7c656d)
Metrics-Module #28
Java 17
 
Installed Addons: (12)
Networks vDEV - 45 (git ade6fbd0)
CMILib v1.2.4.1
InfinityExpansion vDEV - 140 (git 0098d2fb)
AureliumSkills vBeta 1.3.11
ShopGUIPlus v1.80.1
LiteXpansion vDEV - 182 (git d3800398)
WestCore v1.2-SNAPSHOT
Residence v5.1.0.1
FluffyMachines vDEV - 127 (git cf047dcf)
CMI v9.2.6.1
ItemsAdder v3.3.0-beta-r11
HeadLimiter v23

**Comment by EagL3-GIT** [comment]
NOTE: Its not just barrels, it also works with slimefun heads like cargo..., electrical things and so on. 
           But barrels are the fastest way how to dupe big amount in short time.

**Comment by Sefiraat** [comment]
Thanks for the report. 

Please can you split this into two reports. Each clear issue should have it's own item so that can be worked on independently as require. I will close this specific issue in readiness for the new reports due to come in.

When you re-report the issue regarding the Barrels and other Slimefun GUIs, please title it more appropriately as an issue pulling items out from Slimefun GUI's otherwise this may get misdiagnosed as an InfinityExpansion issue and/or delay triage.

I have removed your posts from discord, while the report is appreciated, it's best not to advertise exactly how to dupe items within a forum for players of other servers.

I appreciate your time on this. <3
